# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chol_inv <- function(x) {
    .Call('_challenges_chol_inv', PACKAGE = 'challenges', x)
}

log_like_cpp <- function(params, X, y, tpts) {
    .Call('_challenges_log_like_cpp', PACKAGE = 'challenges', params, X, y, tpts)
}

log_post_cpp <- function(params, X, y, tpts) {
    .Call('_challenges_log_post_cpp', PACKAGE = 'challenges', params, X, y, tpts)
}

MH <- function(MH_draws, proposal_cov, X, y, tpts) {
    .Call('_challenges_MH', PACKAGE = 'challenges', MH_draws, proposal_cov, X, y, tpts)
}

