# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_like_cpp <- function(params, X, y, tpts) {
    .Call('_challenges_log_like_cpp', PACKAGE = 'challenges', params, X, y, tpts)
}

